name: CI Pipeline  # Nom du workflow

on:                # Événements qui déclenchent le workflow
  push:            # Lors d'un push
    branches:
      - main       # Sur la branche main
  pull_request:    # Ou lors d'une pull request vers main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build the application
        run: echo "Building the application..."

  test_job_1:
    runs-on: ubuntu-latest
    needs: build    # Exécute cette étape après "build"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run test job 1
        run: echo "Test réussi pour le job 1"

  test_job_2:
    runs-on: ubuntu-latest
    needs: build    # Exécute cette étape après "build"
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run test job 2
        run: echo "Test réussi pour le job 2"

  deploy:
    runs-on: ubuntu-latest
    needs: [test_job_1, test_job_2]  # Exécute cette étape après les deux jobs de test
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy the application
        run: echo "Déploiement réussi"
