name: CI Pipeline  # Nom du workflow

on:              
  push:        
    branches:
      - main       # La branche principale 
    tags:          # Pour exécuter le déploiement lors d'un tag
      - 'v*'     

jobs:
  build:
    runs-on: ubuntu-latest 
    container:              
      image: docker:latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Build the application
        run: echo "Building the application..."

  test_job_1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run test job 1
        run: echo "Test réussi pour le job 1"

  test_job_2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: |
            ~/.npm
            node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Run test job 2
        run: echo "Test réussi pour le job 2"

  deploy:
    runs-on: ubuntu-latest
    needs: [test_job_1, test_job_2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy the application
        run: |
          echo "Déploiement réussi"
          echo "Environnement de déploiement : ${{ secrets.DEPLOY_ENV }}"
