name: CI Pipeline  # Nom du workflow

on:              
  push:        
    branches:
      - main    
  pull_request:    

env:
  DEPLOY_ENV: ${{ variables.DEPLOY_ENV }} 


jobs:
  build:
    runs-on: ubuntu-latest 
    container:              
      image: docker:latest  
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Build the application
        run: echo "Building the application..."

  test_job_1:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run test job 1
        run: echo "Test réussi pour le job 1"

  test_job_2:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Run test job 2
        run: echo "Test réussi pour le job 2"

  deploy:
    runs-on: ubuntu-latest
    needs: [test_job_1, test_job_2]
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Deploy the application
        run: |
          echo "Déploiement réussi"
          echo "Environnement de déploiement : $DEPLOY_ENV"